# yamllint disable
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-dcgm-diag
  labels:
    app: nvidia-dcgm-diag
spec:
  selector:
    matchLabels:
      name: nvidia-dcgm-diag
  template:
    metadata:
      labels:
        name: nvidia-dcgm-diag
        app: nvidia-dcgm-diag
    spec:
      serviceAccountName: node-list
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            # Multiple matchExpressions ORed between each other. Statements whithin matchExpressions ANDed.
            - matchExpressions:
              - key: cloud.google.com/gke-accelerator
                operator: Exists
                # It will trigger if label value is older than 24 hours (default) ago
                # or label does not exists.
              - key: aiinfra/gpu-healthcheck-valid-till-sec
                operator: Lt
                values:
                - "${CHECK_TIME_EPOCH_SEC}"
              - key: aiinfra/node-not-ready
                operator: DoesNotExist
            - matchExpressions:
              - key: cloud.google.com/gke-accelerator
                operator: Exists
              - key: aiinfra/gpu-healthcheck-valid-till-sec
                operator: DoesNotExist
              - key: aiinfra/node-not-ready
                operator: DoesNotExist
      tolerations:
      - operator: "Exists"
      volumes:
      - name: nvidia-install-dir-host
        hostPath:
          path: /home/kubernetes/bin/nvidia
      containers:
      - image: "us-docker.pkg.dev/gce-ai-infra/health-check/gpu-healthcheck:${IMAGE_TAG}"
        name: "gpu-healthcheck"
        imagePullPolicy: Always
        ports:
        - containerPort: 5555
          hostPort: 5555
        securityContext:
          privileged: true
        volumeMounts:
        - name: nvidia-install-dir-host
          mountPath: /usr/local/nvidia
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: R_LEVEL
          value: "${R_LEVEL}"
        - name: HEALTH_VALIDITY_HOURS
          value: "24"
        - name: DRY_RUN
          value: "${DRY_RUN}"
        resources:
          limits:
            nvidia.com/gpu: !!int 8
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-list
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-list
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-list
  namespace: default
subjects:
- kind: ServiceAccount
  name: node-list
  namespace: default
roleRef:
  kind: ClusterRole
  name: node-list
  apiGroup: rbac.authorization.k8s.io
